"""test

Revision ID: 2a892ef32a65
Revises: 0f5d24ca5153
Create Date: 2024-04-22 12:27:35.240621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a892ef32a65'
down_revision: Union[str, None] = '0f5d24ca5153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('user_account', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('balance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_account', 'amount')
    # ### end Alembic commands ###
