"""test

Revision ID: 6855a19edd52
Revises: 4f96425c8071
Create Date: 2024-04-21 22:44:10.754262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6855a19edd52'
down_revision: Union[str, None] = '4f96425c8071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'amount')
    # ### end Alembic commands ###
