"""test1

Revision ID: dcb087b8a912
Revises: e5633c49282c
Create Date: 2024-04-23 10:11:13.850596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb087b8a912'
down_revision: Union[str, None] = 'e5633c49282c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sender_to', sa.Integer(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_tracker_id'), 'activity_tracker', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_tracker_id'), table_name='activity_tracker')
    op.drop_table('activity_tracker')
    # ### end Alembic commands ###
