"""test

Revision ID: e12e71554d91
Revises: 074855b29f70
Create Date: 2024-04-19 12:36:48.385753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12e71554d91'
down_revision: Union[str, None] = '074855b29f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('book', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('book', 'age')
    # ### end Alembic commands ###
