"""test1

Revision ID: ef36efb8d388
Revises: dcb087b8a912
Create Date: 2024-04-23 10:47:07.295253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef36efb8d388'
down_revision: Union[str, None] = 'dcb087b8a912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_tracker', 'sender_to',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('activity_tracker', 'received_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('activity_tracker_received_by_fkey', 'activity_tracker', type_='foreignkey')
    op.drop_constraint('activity_tracker_sender_to_fkey', 'activity_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'activity_tracker', 'user', ['received_by'], ['email'])
    op.create_foreign_key(None, 'activity_tracker', 'user', ['sender_to'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_tracker', type_='foreignkey')
    op.drop_constraint(None, 'activity_tracker', type_='foreignkey')
    op.create_foreign_key('activity_tracker_sender_to_fkey', 'activity_tracker', 'user', ['sender_to'], ['id'])
    op.create_foreign_key('activity_tracker_received_by_fkey', 'activity_tracker', 'user', ['received_by'], ['id'])
    op.alter_column('activity_tracker', 'received_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('activity_tracker', 'sender_to',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
